modules-left = sp launcher sp bspwm sp net-info sp vpn
modules-center = weather
modules-right = target sp cpu-info ram-info sp battery pulseaudio sp date sp sysmenu sp

[module/launcher]
type = custom/text
content = 
content-padding = 1
click-left = rofi -show drun -show-icons -theme ~/.config/rofi/application/apps.rasi
click-right = /usr/local/bin/settings

[module/sysmenu]
type = custom/text
content = 
content-padding = 1
click-left = ~/.config/rofi/power_menu/power
click-right = ~/.config/rofi/music/player.sh

[module/sp]
type = custom/text
content = "    "

[module/battery]
type = internal/battery
full-at = 99
battery = BAT1
adapter = ACAD
poll-interval = 2
time-format = %H:%M
format-charging = <animation-charging> <label-charging>
;;format-charging-foreground = ${color.fg-alt}
format-charging-background = ${color.bg}
format-charging-padding = 1
format-discharging = <ramp-capacity> <label-discharging>
;;format-discharging-foreground = ${color.fg-alt}
format-discharging-background = ${color.bg}
format-discharging-padding = 1
format-full = <label-full>
format-full-prefix = 
format-full-foreground = ${color.fg-alt}
format-full-background = ${color.bg}
format-full-padding = 1
label-charging = "%percentage%% "
label-discharging = "%percentage%% "
label-full = " Full "
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750


ramp-capacity-0-foreground = ${color.fg-alt}
ramp-capacity-1-foreground = ${color.fg-alt}
ramp-capacity-2-foreground = ${color.fg-alt}
ramp-capacity-3-foreground = ${color.fg-alt}
ramp-capacity-4-foreground = ${color.fg-alt}
ramp-capacity-5-foreground = ${color.fg-alt}
ramp-capacity-6-foreground = ${color.fg-alt}
ramp-capacity-7-foreground = ${color.fg-alt}
ramp-capacity-8-foreground = ${color.fg-alt}
ramp-capacity-9-foreground = ${color.fg-alt}
ramp-capacity-10-foreground = ${color.fg-alt}

animation-charging-0-foreground = ${color.fg-alt}
animation-charging-1-foreground = ${color.fg-alt}
animation-charging-2-foreground = ${color.fg-alt}
animation-charging-3-foreground = ${color.fg-alt}
animation-charging-4-foreground = ${color.fg-alt}
animation-charging-5-foreground = ${color.fg-alt}
animation-charging-6-foreground = ${color.fg-alt}
animation-charging-7-foreground = ${color.fg-alt}
animation-charging-8-foreground = ${color.fg-alt}
animation-charging-9-foreground = ${color.fg-alt}
animation-charging-10-foreground = ${color.fg-alt}

[module/bspwm]
type = internal/bspwm
format = <label-state> <label-mode>
label-focused = %{T13}%{T-}
label-focused-foreground = ${color.active_space}
label-focused-padding = 1
label-occupied = %{T7}%{T-}
label-occupied-foreground = ${color.active_space}
label-occupied-padding = 1
label-urgent = %{T7}%{T-}
label-urgent-foreground = ${color.ac}
label-urgent-padding = 1
label-empty = %{T7}%{T-}
label-empty-foreground = ${color.inactive_space}
label-empty-padding = 1
label-locked = %{T7}%{T-}
label-locked-foreground = ${color.fg}
label-locked-padding = 1
label-sticky = %{T7}%{T-}
label-sticky-foreground = ${color.fg}
label-sticky-padding = 1
label-private = %{T7}%{T-}
label-private-foreground = ${color.fg}
label-private-padding = 1
label-marked = %{T7}%{T-}
label-marked-foreground = ${color.fg}
label-marked-padding = 1

[module/weather]
type = custom/script
interval = 600
format-padding = 1
label = %output%
format = <label>
exec = ~/.config/bin/scripts/weather.sh


[module/net-info]
type = custom/script
exec = ~/.config/bin/scripts/net_display.sh
interval = 2
click-left = ~/.config/bin/scripts/net_toggle.sh



[module/cpu-info]
type = internal/cpu
interval = 1
format = <label>
label-foreground = ${color.fg}
label = %percentage%%

format-prefix = " "
format-prefix-foreground = ${color.fg-alt}


[module/ram-info]
type = internal/memory
interval = 1
format = <label>
label-foreground = ${color.fg}
label = %used%

format-prefix = "   "
format-prefix-foreground = ${color.fg-alt}


[module/date]
type = internal/date
interval = 1

time = "%I:%M %p"
time-alt = "%a, %b %d %I:%M:%S"

format = %{T7}%{T-} <label>
format-foreground = ${color.fg}
format-padding = 1
label = %{A1:#date.toggle:}%{A3:~/.config/bin/scripts/calendar.sh:}%{T2}%time%%{T-}%{A}%{A}
cursor-click = pointer


[module/ewmh]
type = internal/xworkspaces

format = <label-state>

label-active = %{T7}%{T-}
label-active-foreground = ${color.fg}
label-active-padding = 1

label-occupied = %{T7}%{T-}
label-occupied-foreground = ${color.fg-alt}
label-occupied-padding = 1

label-urgent = %{T7}%{T-}
label-urgent-foreground = ${color.ac}
label-urgent-padding = 1

label-empty = %{T7}%{T-}
label-empty-foreground = ${color.fg-alt}
label-empty-padding = 1

[module/vpn]
type = custom/script
interval = 0.1
format-padding = 1
label = %output%
format = <label>
exec = ~/.config/bin/scripts/net_config/vpn.sh
click-left = ~/.config/bin/scripts/copy_ip.sh --myip

[module/artist]
type = custom/script
exec = ~/.config/bin/scripts/music/artist.sh 
interval = 1

[module/playerctl-prev]
type = custom/script
exec = ~/.config/bin/scripts/playerctl-prev.sh
interval = 1
click-left = playerctl previous

[module/playerctl-play]
type = custom/script
exec = ~/.config/bin/scripts/playerctl-play.sh
tail = true
interval = 1
click-left = ~/.config/bin/scripts/playerctl-play.sh --click

[module/playerctl-next]
type = custom/script
exec = ~/.config/bin/scripts/playerctl-next.sh
interval = 1
click-left = playerctl next

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false
format-volume = <label-volume>
format-volume-padding = 1
format-volume-prefix = %{T7}%{T-}
format-volume-prefix-foreground = ${color.fg-alt}
label-volume = %{T1} %percentage%%%{T-}
label-volume-foreground = ${color.fg}
format-muted = <label-muted>
format-muted-padding = 1
format-muted-prefix = %{T7}%{T-}
format-muted-prefix-foreground = ${color.fg}
label-muted = %{T1} %percentage%%%{T-}
label-muted-foreground = ${color.fg}
click-right = pavucontrol&

[module/target]
type = custom/script
interval = 0.1
format-padding = 1
label = %output%
format = <label>
exec = ~/.config/bin/scripts/target.sh
click-left = ~/.config/bin/scripts/copy_ip.sh --target

[module/xbacklight]
type = internal/xbacklight
format = <label>
format-padding = 1
format-prefix = %{T7}%{T-}
format-prefix-foreground = ${color.fg}
label = %{T1} %percentage%%%{T-}
label-foreground = ${color.fg}
