;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; └────────────────────────────────────────────────────────────┘


[color]
bg = #161616
fg = #ffffff
fg-alt = #f4d76b

transparent = #40000000
launch = #f4d76b

active_space = #f4d76b
inactive_space = #b8b8b8
ac = #FEC006

;Cuts
volume_level = #aaaaaa
volume_full = #f4d76b

;Shapes
shade1 = #A87E00
shade2 = #D4A800
shade3 = #ECC83A
shade4 = #f4d76b


;Pacman
mb     = #232323
pacman = #aaaaaa
ghost  = #f4d76b
points = #aaaaaa
power  = #f4d76b
pc_cpu = #f4d76b
pc_ram = #f4d76b
volume = #f4d76b
play   = #f4d76b
play_alt = #f4d76b