#!/usr/bin/env bash

# Special Character ' ㅤ ' 

kitty_style(){
    local setting="$1"
    if [[ "$setting" == "bg-alt" ]]; then
        sed -i -e "s/background .*/background #000000/g" ~/.config/theme/colors/kitty.ini
    else
        sed -i -e "s/background_opacity .*/background_opacity $setting/g" ~/.config/kitty/kitty.conf
    fi
    kill -USR1 $(pgrep -x kitty)
    pkill -USR1 cava 2>/dev/null
}

picom_style(){
    local style="$1"
    if [[ "$style" == "100" ]]; then
        cp -r ~/.BSPWM/installer/Config/picom/blur_picom.conf ~/.config/picom/picom.conf
    else
        cp -r ~/.BSPWM/installer/Config/picom/picom.conf ~/.config/picom/picom.conf
    fi
}

border_style(){
    local border="$1"
    sed -i -e "s/bspc config border_width.*/bspc config border_width $border/g" ~/.config/bspwm/bspwmrc
    bspc wm -r
}

interpreter_shell(){
    local inter="$1"
    sed -i -e "s/shell .*/shell $inter/g" ~/.config/kitty/kitty.conf
}

kill_(){
    local bar="$1"
    if [[ "$bar" == "polybar" ]]; then
        pkill -x polybar
        pkill -f "$HOME/.config/polybar/launch.sh"
    else
        pkill -x eww
        pkill -f "$HOME/.config/eww/Bar.sh" 
    fi
}

MENU="$(rofi -no-config -no-lazy-grab -sep "|" -dmenu -i -p ' Settings' \
-theme-str "entry { placeholder: \"BSPWM\"; }" -theme $HOME/.config/rofi/notes/note.rasi \
<<< "󰄛 KittyㅤTransparencyㅤ80%|󰄛 KittyㅤTransparencyㅤ50%|󰄛 KittyㅤTransparencyㅤ0%|󰄛 KittyㅤBackgroundㅤAlt|󱂬 PicomㅤBlurㅤ100%| \
󱂬 PicomㅤBlurㅤ0%|󰢡 EnableㅤBorders|󰢤 DisableㅤBorders󱓇 KillㅤPolybar|󱓇 KillㅤEWW|")"
            case "$MENU" in
				*KittyㅤTransparencyㅤ80%) kitty_style "0.5" ;;
				*KittyㅤTransparencyㅤ50%) kitty_style "0.8" ;;
                *KittyㅤTransparencyㅤ0%) kitty_style "10" ;;
                *KittyㅤBackgroundㅤAlt) kitty_style "bg-alt" ;;
                *PicomㅤBlurㅤ100%) picom_style "100" ;;
                *PicomㅤBlurㅤ0%) picom_style "0" ;;
                *EnableㅤBorders) border_style "2.5" ;;
                *DisableㅤBorders) border_style "0" ;;
                *KillㅤPolybar) kill_ "polybar" ;;
                *KillㅤEWW) kill_ "eww" ;;
            esac 