;; ┌────────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▄█░█▀█░█▀▄░█░█░█░░░█▀▀░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░█░█░█░█░█░█░█░█░░░█▀▀░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀░▀░▀▀▀░▀▀░░▀▀▀░▀▀▀░▀▀▀░▀▀▀│
;; └────────────────────────────────────────────────────────────────┘

[module/launcher]
type = custom/text
content = 
content-background = ${color.bg}
content-foreground = ${color.launch}
content-padding = 1
click-left = rofi -show drun -show-icons -theme ~/.config/rofi/application/apps.rasi
click-right = /usr/local/bin/settings

[module/sysmenu]
type = custom/text
content = 
content-background = ${color.bg}
content-foreground = ${color.fg}
content-padding = 1
click-left = ~/.config/rofi/power_menu/power
click-right = ~/.config/rofi/music/player.sh

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/decor-glyph]
type = custom/text
content-background = ${color.transparent}
content-foreground = ${color.bg}

[module/decor1]
inherit = module/decor-glyph
content = "%{T3}%{T-}"

[module/decor2]
inherit = module/decor-glyph
content = "%{T3}%{T-}"

[module/decor3]
inherit = module/decor-glyph
content = "%{T3}%{T-}"

[module/decor4]
inherit = module/decor-glyph
content = "%{T3}%{T-}"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
[module/cpu-info]
type = internal/cpu
interval = 1
format = <label>
label-background = ${color.bg}
label-foreground = ${color.fg}
label = %percentage%%

format-prefix = "  "
format-prefix-background = ${color.bg}
format-prefix-foreground = ${color.fg-alt}


[module/ram-info]
type = internal/memory
interval = 1
format = <label>
label-background = ${color.bg}
label-foreground = ${color.fg}
label = %used%

format-prefix = "   "
format-prefix-background = ${color.bg}
format-prefix-foreground = ${color.fg-alt}


[module/sp]
type = custom/text
content = "  "
content-background = ${color.bg}

[module/battery]
type = internal/battery
full-at = 99
battery = BAT1
adapter = ACAD
poll-interval = 2
time-format = %H:%M
format-charging = <animation-charging> <label-charging>
;;format-charging-foreground = ${color.fg-alt}
format-charging-background = ${color.bg}
format-charging-padding = 1
format-discharging = <ramp-capacity> <label-discharging>
;;format-discharging-foreground = ${color.fg-alt}
format-discharging-background = ${color.bg}
format-discharging-padding = 1
format-full = <label-full>
format-full-prefix = 
format-full-foreground = ${color.fg-alt}
format-full-background = ${color.bg}
format-full-padding = 1
label-charging = "%percentage%% "
label-discharging = "%percentage%% "
label-full = " Full "
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750


ramp-capacity-0-foreground = ${color.fg-alt}
ramp-capacity-1-foreground = ${color.fg-alt}
ramp-capacity-2-foreground = ${color.fg-alt}
ramp-capacity-3-foreground = ${color.fg-alt}
ramp-capacity-4-foreground = ${color.fg-alt}
ramp-capacity-5-foreground = ${color.fg-alt}
ramp-capacity-6-foreground = ${color.fg-alt}
ramp-capacity-7-foreground = ${color.fg-alt}
ramp-capacity-8-foreground = ${color.fg-alt}
ramp-capacity-9-foreground = ${color.fg-alt}
ramp-capacity-10-foreground = ${color.fg-alt}

animation-charging-0-foreground = ${color.fg-alt}
animation-charging-1-foreground = ${color.fg-alt}
animation-charging-2-foreground = ${color.fg-alt}
animation-charging-3-foreground = ${color.fg-alt}
animation-charging-4-foreground = ${color.fg-alt}
animation-charging-5-foreground = ${color.fg-alt}
animation-charging-6-foreground = ${color.fg-alt}
animation-charging-7-foreground = ${color.fg-alt}
animation-charging-8-foreground = ${color.fg-alt}
animation-charging-9-foreground = ${color.fg-alt}
animation-charging-10-foreground = ${color.fg-alt}

[module/playerctl]
type = custom/script
exec = ~/.config/bin/scripts/music/artist.sh 
interval = 1
format-foreground = ${color.fg}
format-background = ${color.bg}
cursor-click = pointer

[module/prev]
type = custom/text
content = " "
content-background = ${color.bg}
content-foreground = ${color.fg}
content-font = 4
click-left = playerctl previous
cursor-click = pointer

[module/play]
type = custom/script
exec = ~/.config/bin/scripts/music/play.sh
tail = true
interval = 1
format-foreground = ${color.fg}
click-left = ~/.config/bin/scripts/music/play.sh --click
format-background = ${color.bg}
cursor-click = pointer

[module/next]
type = custom/text
content = ""
content-background = ${color.bg}
content-foreground = ${color.fg}
content-font = 4
click-left = playerctl next
cursor-click = pointer

[module/cava]
type = custom/script
tail = true
exec = $HOME/.config/bin/scripts/cava.sh
format-background = ${color.bg}
format = <label>
format-font = 1
label = %output%

[module/weather]
type = custom/script
tail = true
interval = 600
exec = ~/.config/bin/scripts/weather.sh
format = <label>
label = %output%
format-background = ${color.bg}
format-foreground = ${color.fg}
format-font = 1
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/workspaces]
type = internal/xworkspaces
pin-workspaces = true
enable-click = true
enable-scroll = true
icon-0 = I;
icon-1 = II; 
icon-2 = III;  
icon-3 = IV;
icon-4 = V;
icon-5 = VI;
format = <label-state>
format-background = ${color.bg}
format-padding = 0
label-monitor = %name%
label-active = %icon%
label-active-foreground = ${color.active_space}
label-active-overline = ${color.active_space}
label-occupied = %icon%
label-occupied-foreground = ${color.active_space}
label-urgent = %icon%
label-urgent-foreground = ${color.ac}
label-empty = %icon%
label-empty-foreground = ${color.fg}
label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1
label-empty-padding = 1

[module/net-info]
type = custom/script
format-background = ${color.bg}
exec = ~/.config/bin/scripts/net_display.sh
interval = 2
click-left = ~/.config/bin/scripts/net_toggle.sh

[module/vpn]
type = custom/script
interval = 0.1
format-background = ${color.bg}
format-padding = 1
label = %output%
format = <label>
exec = ~/.config/bin/scripts/net_config/vpn.sh
click-left = ~/.config/bin/scripts/copy_ip.sh --myip

[module/target]
type = custom/script
interval = 0.1
format-background = ${color.bg}
format-padding = 1
label = %output%
format = <label>
exec = ~/.config/bin/scripts/target.sh
click-left = ~/.config/bin/scripts/copy_ip.sh --target

[module/date]
type = internal/date
interval = 1.0
time = " %I:%M %p"
time-alt = " %a, %d %b %Y"
format = <label>
format-foreground = ${color.fg}
format-background = ${color.bg}
format-padding = 1
label = %{A1:#date.toggle:}%{A3:~/.config/bin/scripts/calendar.sh:}%{T2}%time%%{T-}%{A}%{A}
cursor-click = pointer


[module/filesystem]
type = internal/fs
mount-0 = /
interval = 30
fixed-values = true
format-mounted = <label-mounted>
format-mounted-prefix = 
format-mounted-foreground = ${color.fg}
format-mounted-background = ${color.bg}
format-mounted-padding = 1
format-unmounted = <label-unmounted>
format-unmounted-prefix = 
format-unmounted-foreground = ${color.fg}
format-unmounted-background = ${color.bg}
format-unmounted-padding = 1
label-mounted = " %free%"
label-unmounted = " %mountpoint%: not mounted"

[module/temperature]
type = internal/temperature
interval = 0.5
thermal-zone = 0
hwmon-path = /sys/devices/pci0000:00/0000:00:01.3/0000:01:00.0/hwmon/hwmon0/temp1_input
warn-temperature = 65
units = true
format = <ramp> <label>
format-background = ${color.bg}
format-padding = 1
format-warn = <ramp> <label-warn>
format-warn-background = ${color.bg}
format-warn-padding = 1
label = %temperature-c%
label-warn = "%temperature-c%"
label-warn-foreground = ${color.red}
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 


[module/volume]
type = internal/alsa
master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default
master-mixer = Master
interval = 5
format-volume = <ramp-volume> <bar-volume>
format-volume-background = ${color.bg}
format-volume-padding = 1
format-muted = <label-muted>
format-muted-prefix = 
format-muted-foreground = ${color.fg}
format-muted-background = ${color.bg}
format-muted-padding = 1
label-volume = %percentage%%
label-muted = " Muted"
label-muted-foreground = ${color.fg}
ramp-volume-foreground = ${color.fg}
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
bar-volume-format = ${bar.format}
bar-volume-width = ${bar.width}
bar-volume-gradient = false
bar-volume-indicator = ${bar.indicator}
bar-volume-indicator-foreground = ${color.fg}
bar-volume-fill = ${bar.fill}
bar-volume-foreground-0 = ${color.volume_full}
bar-volume-foreground-1 = ${color.volume_full}
bar-volume-foreground-2 = ${color.volume_full}
bar-volume-foreground-3 = ${color.volume_full}
bar-volume-foreground-4 = ${color.volume_full}
bar-volume-empty = ${bar.empty}
bar-volume-empty-foreground = ${color.volume_level}
ramp-headphones-0 = 
